FROM clickhouse/clickhouse-server:latest

# 复制自定义设置
COPY clickhouse_config.xml /etc/clickhouse-server/config.d/
COPY clickhouse_users.xml /etc/clickhouse-server/users.d/

# 复制初始化SQL脚本
COPY init_db.sql /docker-entrypoint-initdb.d/

# 设置权限
RUN chmod 644 /etc/clickhouse-server/config.d/clickhouse_config.xml \
    && chmod 644 /etc/clickhouse-server/users.d/clickhouse_users.xml \
    && chmod 644 /docker-entrypoint-initdb.d/init_db.sql 